<!-- php code to convert the generated bytes to jpg format and make image downloadable -->
<?php

    //form is submitted to the same page
    if(isset($_POST['download'])){

        //get the posted data
        $imgUrl = $_POST['imgUrl'];
        $ch = curl_init($imgUrl); //initialize the cilent url
        curl_setopt($ch, CURLOPT_RETURNTRANSFER,1); //transfers data as the return value
        $download = curl_exec($ch); //execute the curl
        curl_close($ch); //close the curl connection

        // conversion to jpg format
        header('Content-type: image/jpg');
        header('Content-Disposition: attachment; filename="thumbnail.jpg"');
        echo $download; //downloads the image
    }
?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Video Thumbnail Downloader</title>
    <link rel="stylesheet" href="style.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <script src="script.js" defer></script>
  </head>
  <body>
    <form action=<?php echo $_SERVER['PHP_SELF']; ?> method="POST">
      <header>Download Thumbnail</header>
      <div class="url-input">
        <span class="title">Paste video url:</span>
        <div class="field">
          <input
            type="text"
            placeholder="https://www.youtube.com/watch?v=lqwdD2ivIbM"
            required
          />
          <input class="hidden-input" type="hidden" name="imgUrl" />
          <span class="bottom-line"></span>
        </div>
      </div>
      <div class="preview-area">
        <img class="thumbnail" src="" alt="" />
        <i class="icon fas fa-cloud-download-alt"></i>
        <span>Paste video url to see preview</span>
      </div>
      <div>
        <button class="download-btn" type="submit" name="download">
          Download Thumbnail
        </button>
      </div>
    </form>
  </body>
</html>
